GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjgzMzE2MDgsImV4cCI6MTcyODMzNTIwOCwiYXVkIjoiNDciLCJpc3MiOiJub2RlLXRpbWVseSJ9.ii5fBKJDPvsKMe0UdhyaVfG6orAx3ytDckwBHTKraxk

### 404
GET http://localhost:3000/hello_world

### Login Route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "1223bhw32wf2sf2@gmail.com",
    "password": "1232"
}

### Register Route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email" : "1223bhw32wf2sf2@gmail.com",
    "password": "1232"
}

### Refresh Token Route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjgzMzE1ODgsImV4cCI6MTc1OTg4OTE4OCwiYXVkIjoiNDciLCJpc3MiOiJub2RlLXRpbWVseSJ9.Fa2XINQwT7r9IfnSdwkbGuaf0zuJQRwknkYK91W70g4"
}

### Logout Route
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjgzMzE2NzIsImV4cCI6MTc1OTg4OTI3MiwiYXVkIjoiNDciLCJpc3MiOiJub2RlLXRpbWVseSJ9.MDD5gKSO15B61zRmopyF9ij0goUQN4kzgDgKaQECwZ8"
}
